// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxUmwpa-zRJ-G6ufcW_adCHGt-d3I7fs',
    appId: '1:535053449705:web:5a1778e7f938c60c42f378',
    messagingSenderId: '535053449705',
    projectId: 'notekeeper-flutterdemo',
    authDomain: 'notekeeper-flutterdemo.firebaseapp.com',
    storageBucket: 'notekeeper-flutterdemo.appspot.com',
    measurementId: 'G-F6E25MGQVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxbAtmxBOxw5q8uqBNmVJduoKD-CSHuRQ',
    appId: '1:535053449705:android:06113416e11aac6e42f378',
    messagingSenderId: '535053449705',
    projectId: 'notekeeper-flutterdemo',
    storageBucket: 'notekeeper-flutterdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ7ZZMwDEX6Mx4J-kX52aHHqZxOYTW1tA',
    appId: '1:535053449705:ios:0df693859d78210542f378',
    messagingSenderId: '535053449705',
    projectId: 'notekeeper-flutterdemo',
    storageBucket: 'notekeeper-flutterdemo.appspot.com',
    iosClientId: '535053449705-df34l42cs35hidputuahu7e6hkhipdlb.apps.googleusercontent.com',
    iosBundleId: 'notekeeper',
  );
}
